#!/bin/sh
ssh ubuntu@13.209.7.68 <<EOF
    cd ~/nest-jenkins		
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh 
    nvm install 17.5.0
    ls
    rm -rf node_modules
    npm install
    npm install -g typescript
    npm install -g ts-node
    npm install -g pm2
    pm2 install typescript
    pm2 restart ecosystem.config.js
    exit
EOF
